import { Bags, Token } from "arkham-odds";

export const AvailableBags: Array<[string, Token[]]> = [
  ["Night of the Zealot (Easy)", Bags.NightOfTheZealot.Easy],
  ["Night of the Zealot (Standard)", Bags.NightOfTheZealot.Standard],
  ["Night of the Zealot (Hard)", Bags.NightOfTheZealot.Hard],
  ["Night of the Zealot (Expert)", Bags.NightOfTheZealot.Expert],
  ["The Dunwich Legacy (Easy)", Bags.TheDunwichLegacy.Easy],
  ["The Dunwich Legacy (Standard)", Bags.TheDunwichLegacy.Standard],
  ["The Dunwich Legacy (Hard)", Bags.TheDunwichLegacy.Hard],
  ["The Dunwich Legacy (Expert)", Bags.TheDunwichLegacy.Expert],
  ["The Path to Carcosa (Easy)", Bags.ThePathToCarcosa.Easy],
  ["The Path to Carcosa (Standard)", Bags.ThePathToCarcosa.Standard],
  ["The Path to Carcosa (Hard)", Bags.ThePathToCarcosa.Hard],
  ["The Path to Carcosa (Expert)", Bags.ThePathToCarcosa.Expert],
  ["The Forgotten Age (Easy)", Bags.TheForgottenAge.Easy],
  ["The Forgotten Age (Standard)", Bags.TheForgottenAge.Standard],
  ["The Forgotten Age (Hard)", Bags.TheForgottenAge.Hard],
  ["The Forgotten Age (Expert)", Bags.TheForgottenAge.Expert],
  ["The Circle Undone (Easy)", Bags.TheCircleUndone.Easy],
  ["The Circle Undone (Standard)", Bags.TheCircleUndone.Standard],
  ["The Circle Undone (Hard)", Bags.TheCircleUndone.Hard],
  ["The Circle Undone (Expert)", Bags.TheCircleUndone.Expert],
  ["Curse of the Rougarou (Standard)", Bags.CurseOfTheRougarou.Standard],
  ["Curse of the Rougarou (Hard)", Bags.CurseOfTheRougarou.Hard],
  ["Carnevale of Horrors (Standard)", Bags.CarnevaleOfHorrors.Standard],
  ["Carnevale of Horrors (Hard)", Bags.CarnevaleOfHorrors.Hard],
  ["The Labyrinths of Lunacy (Standard)", Bags.TheLabyrinthsOfLunacy.Standard],
  ["The Labyrinths of Lunacy (Hard)", Bags.TheLabyrinthsOfLunacy.Hard],
  ["Guardians of the Abyss (Standard)", Bags.GuardiansOfTheAbyss.Standard],
  ["Guardians of the Abyss (Hard)", Bags.GuardiansOfTheAbyss.Hard]
];
